In [1]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Show the numpy array shape

A.shape

(3, 3)

In [6]:
# Show the numpy array size

A.size

9

In [7]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [8]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [9]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [10]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [11]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [13]:
Z = np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [15]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [17]:
Z = np.dot(A,B)
Z

array([[10, 36],
       [20, 66],
       [30, 96]])

In [18]:
# Calculate the sine of Z

np.sin(Z)

array([[-0.54402111, -0.99177885],
       [ 0.91294525, -0.02655115],
       [-0.98803162,  0.98358775]])

In [19]:
# Get the transposed of C

B.T

array([[ 1,  1, -1],
       [ 1,  1,  1]])

In [1]:
import pandas as pd

In [4]:
KNN_jss = .6
KNN_f1 =.635
DT_jss =.7
DT_f1 = .8333333333333
SVM_jss = .9345
SVM_f1 = .77777776
LR_jss = .57
LR_f1 = .63333
LR_ll = .89

In [2]:
def csvDf(dat,**kwargs): 
  from numpy import array
  data = array(dat)
  if data is None or len(data)==0 or len(data[0])==0:
    return None
  else:
    return pd.DataFrame(data[1:,1:],index=data[1:,0],columns=data[0,1:],**kwargs)

In [7]:
data = [['Algorithm','Jaccard','F1-Score','LogLoss'],['KNN',KNN_jss,KNN_f1,'NA'],
     ['DecisionTree',DT_jss,DT_f1,'NA'],['SVM',SVM_jss,SVM_f1,'NA'],['LogRegression',LR_jss,LR_f1,LR_ll] ]
csvDf(data)

Jaccard         F1-Score LogLoss
KNN               0.6            0.635      NA
DecisionTree      0.7  0.8333333333333      NA
SVM            0.9345       0.77777776      NA
LogRegression    0.57          0.63333    0.89

In [5]:
print ("Algorithm	Jaccard 	F1-score	       LogLoss")
print ()
print ("KNN 	        %1.7f 	%1.7f 	       NA"% (KNN_jss,KNN_f1))
print ("DecisionTree	%1.7f 	%1.7f 	       NA"% (DT_jss,DT_f1))
print ("SVM 	        %1.7f 	%1.7f 	       NA"% (SVM_jss,SVM_f1))
print ("LogRegression 	%1.7f 	%1.7f 	       %1.7f"% (LR_jss,LR_f1, LR_ll))

Algorithm	Jaccard 	F1-score	       LogLoss

KNN 	        0.6000000 	0.6350000 	       NA
DecisionTree	0.7000000 	0.8333333 	       NA
SVM 	        0.9345000 	0.7777778 	       NA
LogRegression 	0.5700000 	0.6333300 	       0.8900000
